# Generated by Django 3.1.1 on 2020-09-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoin',
            name='assert_id_base',
        ),
    ]
