# Generated by Django 3.1.1 on 2020-09-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0002_remove_bitcoin_assert_id_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoin',
            name='assert_id_quote',
        ),
    ]
