# Generated by Django 3.1.1 on 2020-09-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0004_bitcoin_assert_id_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='assert_id_quote',
            field=models.CharField(default='', max_length=100),
        ),
    ]
