# Generated by Django 3.1.1 on 2020-09-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0006_auto_20200916_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoin',
            name='rate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
